name: InstiApp
description: Flutter App for Indian Institute of Technology, Bombay

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.5+22

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  outline_material_icons: ^0.1.0
  url_launcher: ^4.0.1
  flutter_webview_plugin: ^0.3.0+2
  http: ^0.12.0
  jaguar_retrofit: 2.5.12
  jaguar_serializer: ^2.2.4
  rxdart: ^0.19.0
  flutter_html: ^0.8.2
  markdown: ^2.0.2
  shared_preferences: ^0.4.3
  date_format: ^1.0.5
  share: ^0.5.3
  photo_view: ^0.2.1
  flutter_calendar_carousel: ^1.3.10
  google_maps_flutter: ^0.0.3+3
  flutter_google_places: ^0.1.4+1
  location: ^1.4.1
  flutter_material_color_picker: ^0.0.3+1
  flutter_typeahead: ^0.5.1
  image_picker: ^0.4.12+1
  firebase_messaging: ^2.1.0
  flutter_local_notifications: ^0.4.4+2
  path_provider: ^0.4.1
  cached_network_image: ^0.5.1
  flutter_image_compress: ^0.2.3
  uni_links: ^0.1.4
  flutter_dynamic_icon: ^0.2.0+1
  jaguar_flutter_asset: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  jaguar_serializer_cli: ^2.2.4
  jaguar_retrofit_gen: ^2.5.10
  build_runner: ^1.0.0
  test: ^1.5.1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/login/
    - assets/map/
    - assets/map/assets/
    - assets/map/assets/map/
  fonts: 
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans/IBMPlexSans-Regular.ttf
        - asset: fonts/IBMPlexSans/IBMPlexSans-Italic.ttf
          style: italic
        - asset: fonts/IBMPlexSans/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: fonts/IBMPlexSans/IBMPlexSans-BoldItalic.ttf
          style: italic
          weight: 700 

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
