name: InstiApp
description: Flutter App for Indian Institute of Technology, Bombay

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.8.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  outline_material_icons: ^0.1.0
  url_launcher: ^4.0.1
  flutter_webview_plugin: ^0.3.5
  http: ^0.12.0
  jaguar_retrofit: 2.8.6
  jaguar_serializer: 2.2.12
  rxdart: ^0.20.0
  flutter_html: ^0.9.6
  markdown: ^2.0.2
  shared_preferences: ^0.5.1+2
  date_format: ^1.0.6
  share: ^0.6.0
  photo_view: ^0.2.2
  flutter_calendar_carousel: 1.3.17
  google_maps_flutter: ^0.5.0
  flutter_google_places: ^0.2.1
  location: ^2.3.2
  flutter_material_color_picker: ^0.0.5
  flutter_typeahead: ^1.4.0
  image_picker: ^0.5.0
  firebase_messaging: ^4.0.0
  flutter_local_notifications: ^0.6.0
  path_provider: ^0.5.0
  cached_network_image: ^0.7.0
  flutter_image_compress: ^0.2.4
  uni_links: ^0.2.0
  flutter_dynamic_icon: ^0.2.0+1
  jaguar_flutter_asset: ^2.2.0
  device_calendar: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  jaguar_serializer_cli: 2.2.5
  jaguar_retrofit_gen: 2.8.6
  build_runner: ^1.0.0
  # test: 1.6.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/login/
    - assets/map/
    - assets/map/assets/
    - assets/map/assets/map/
  fonts: 
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans/IBMPlexSans-Regular.ttf
        - asset: fonts/IBMPlexSans/IBMPlexSans-Italic.ttf
          style: italic
        - asset: fonts/IBMPlexSans/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: fonts/IBMPlexSans/IBMPlexSans-BoldItalic.ttf
          style: italic
          weight: 700 
  uses-material-design: true